pull_request_title: Update translations from Crowdin
append_commit_message: false
commit_message: Updated %language% translations.

files:
  - source: Skyblock-Classic-Edition/lang/_default_.json
    translation: Skyblock-Classic-Edition/lang/%locale_with_underscore%.json
