pull_request_title: Update translations from Crowdin
files:
  - source: /Resources Pack/assets/minecraft/lang/en_us.json
    translation: /Resources Pack/assets/minecraft/lang/%locale_with_underscore%.json
    multilingual: 1
