name: Skyblock Classic Edition - Nightly Building System

on:
  push:
    branches: [ "main" ]

jobs:
  zip-n-pull:
    name: Zip and Pull
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../ # I added this
          rm -rf <repository_name>.zip
          zip -r <repository_name>.zip <repository_name> -x ".git/*" ".github/*"