name: Skyblock Nightly Building

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/upload-artifact@v4
      with:
        name: Nightly Actions
        path: Skyblock\_Classic\_Edition\_Nightly\_Building.zip