name: Skyblock Classic Edition - Nightly Building System

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
        with:
          args: |
            rm -rf Skyblock_Classic_Edition.zip
            zip -r Skyblock_Classic_Edition.zip Skyblock Classic Edition 
            -x ".git/*" ".github/*"
      - uses: actions/upload-artifact@v4
        with:
          name: Nightly Actions Run (Output)
          path: Skyblock Classic Edition.zip