name: Create Builds

on:
  push:
    paths:
      - 'datapacks/Skyblock CE datapacks/data/skyblock/function/versions/changelog/building_version.json'

jobs:
  check_changes:
    runs-on: ubuntu-24.04
    outputs:
      release_changed: ${{ steps.check.outputs.release_changed }}
      nightly_changed: ${{ steps.check.outputs.nightly_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Get file changes
        id: changed-files
        run: |
          DIFF=$(git diff HEAD^ HEAD -- "datapacks/Skyblock CE datapacks/data/skyblock/function/versions/changelog/building_version.json")
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check changes
        id: check
        run: |
          DIFF="${{ steps.changed-files.outputs.diff }}"
          if echo "$DIFF" | grep -q '"Release Building"'; then
            echo "release_changed=true" >> $GITHUB_OUTPUT
          else
            echo "release_changed=false" >> $GITHUB_OUTPUT
          fi
          if echo "$DIFF" | grep -q '"Nightly Building"'; then
            echo "nightly_changed=true" >> $GITHUB_OUTPUT
          else
            echo "nightly_changed=false" >> $GITHUB_OUTPUT
          fi

  release_build:
    needs: check_changes
    if: needs.check_changes.outputs.release_changed == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Upload release content
        uses: actions/upload-artifact@v4
        with:
          name: Skyblock_CE_Latest
          path: |
            datapacks/**/*
            !.git/**
            !.github/**
            !.gitignore
            !.worlds/**
            !Resources Pack/**
            !crowdin.yml
            !spyglass.json
            !*.zip
            !.DS_Store
          if-no-files-found: error
          retention-days: 90

  nightly_build:
    needs: check_changes
    if: needs.check_changes.outputs.nightly_changed == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Upload nightly content
        uses: actions/upload-artifact@v4
        with:
          name: Skyblock_CE_Nightly_Snapshots
          path: |
            datapacks/**/*
            !.git/**
            !.github/**
            !.gitignore
            !.worlds/**
            !Resources Pack/**
            !crowdin.yml
            !spyglass.json
            !*.zip
            !.DS_Store
          if-no-files-found: error
          retention-days: 90