name: Skyblock Classic Edition - Nightly Building System

on:
  push:
    branches: [ "main" ]

jobs:
  zip-n-pull:
    name: Zip and Pull
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../ # I added this
          rm -rf Skyblock\_Classic\_Edition\_Nightly\_Building.zip
          zip -r Skyblock\_Classic\_Edition\_Nightly\_Building.zip Skyblock\_Classic\_Edition\_Nightly\_Building -x ".git/*" ".github/*"