name: Skyblock Classic Edition - Nightly Building System

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Nightly Actions Run (Output)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - run: |
          rm -rf <repository_name>.zip
          zip -r <repository_name>.zip <repository_name> -x ".git/*" ".github/*"
      - uses: actions/upload-artifact@v4
        with:
          name: Nightly Actions Run (Output)
          path: Skyblock\_Classic\_Edition\_Nightly\_Building.zip