name: Skyblock Classic Edition - Nightly Building System

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: zip -r [Skyblock-Classic-Edition.git]
    - uses: actions/upload-artifact@v4
      with:
        name: Nightly Actions Run (Output)
        path: Skyblock\_Classic\_Edition\_Nightly\_Building.zip