name: Skyblock Classic Edition - Nightly Building System

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - run: |
          cd Skyblock Classic Edition
          rm -rf Skyblock_Classic_Edition.zip
          zip -r Skyblock_Classic_Edition.zip Skyblock_Classic_Edition -x ".git/*" ".github/*"
      - uses: actions/upload-artifact@v4
        with:
          name: Nightly Actions Run (Output)
          path: Skyblock_Classic_Edition_Nightly_Building.zip