name: Create Nightly Release Build

on:
  push:
    paths:
      - 'datapacks/Skyblock CE datapacks/data/skyblock/function/versions/changelog/building_version.json'

jobs:
  check_changes:
    runs-on: ubuntu-24.04
    outputs:
      should_build: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Get file changes
        id: changed-files
        run: |
          DIFF=$(git diff HEAD^ HEAD -- "datapacks/Skyblock CE datapacks/data/skyblock/function/versions/changelog/building_version.json")
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check if Nightly Building changed
        id: check
        run: |
          if echo "${{ steps.changed-files.outputs.diff }}" | grep -q '"Nightly Building"'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_changes
    if: needs.check_changes.outputs.should_build == 'true'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Upload folder content as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyblock_CE_Nightly_Snapshots
          path: |
            **/*
            !.git/**
            !.github/**
            !.gitignore
            !.worlds/**
            !Resources Pack/**
            !crowdin.yml
            !spyglass.json
            !*.zip
            !.DS_Store
          if-no-files-found: error